services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: diabetes_db
      MYSQL_ROOT_PASSWORD: riad3214321?
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app-network

  web:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: riad3214321?
      DB_NAME: diabetes_db
        
    networks:
      - app-network


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-network


networks:
  app-network:

volumes:
  db_data:
